### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vedmalex** [lirown/graphql-custom-directives#10]
in complex schema with complex types that references one to each other.

**Comment by josercarmo** [comment]
Hi @vedmalex , i have the same problem, and graphql is a graph lol, the way this being visited the nodes are wrong, I managed to solve it in a not so pretty way, so I did not pull request yet, but if you need too much, is this:
```javascript
function wrapFieldsWithMiddleware(fields,parent) {
    for (let label in fields) {
        let field = fields.hasOwnProperty(label) ? fields[label] : null;

        if(field.attachedDirective) continue;

        field.attachedDirective = true;
        field.resolve = resolveMiddlewareWrapper(field.resolve, field.directives);

        if (!!field && typeof field == 'object') {
            let colunm = parent ? parent + "." + label : label
            let count = (colunm.match(/\./g) || []).length;
            if (field.type._fields) {
                wrapFieldsWithMiddleware(field.type._fields,colunm)
            } else if (field.type.ofType && field.type.ofType._fields) {
                if(count >= 6) continue;
                wrapFieldsWithMiddleware(field.type.ofType._fields,colunm);
            }
        }
    }
}
```

The "ugly" is count>=6....where six is the level max to visit....anyway...I hope it help!

**Comment by vedmalex** [comment]
@joserochadocarmo, we need somehow need to have hash(key:values) with visited item and check if it is already visited or not, and send this hash to the recursion call.

**Comment by vedmalex** [comment]
@joserochadocarmo see the changes it is working with any depth and compatible with latest graphql
